---
title: "Twitter dog - w2"
author: "Li huiyan"
date: "14/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rtweet)
```

## Data import

Step 1. collect tweets about dog

```{r}
auth_setup_default()
dog_tweets<-search_tweets(
  q="dog",
  n=10000,
  include_rts = FALSE,
  lang="en",
  retryonratelimit = TRUE
)

```


```{r}
#look at first 6 obs
dog_tweets%>%
  head()

#look at structure
dog_tweets%>%
  str()

  
dog_short<-dog_tweets%>%
  select(user_id, screen_name, created_at, text, favourites_count, retweet_count)

dog_short%>%write_csv("dog_short_14_08_22.csv")
dog_tweets<-read_csv("14_08_2022.csv")

```

### Explore frequency of tweets


```{r}
ts_plot(all_data, "hours") +
  labs(x = NULL, y = NULL,
       title = "Frequency of tweets with dog",
       subtitle = paste0(format(min(all_data$created_at), "%d %B %Y"), " to ", format(max(all_data$created_at),"%d %B %Y")),
       caption = "dog tweets Data collected from Twitter") +
  theme_minimal()
```

### Most frequently shared link

```{r}
dog_tweets %>% 
  filter(!is.na(urls_expanded_url)) %>% 
  count(urls_expanded_url, sort = TRUE) %>% 
  top_n(5)
```
### Most retweeted tweet

```{r}
dog_tweets %>% 
  arrange(-retweet_count) %>%
  slice(1) %>% 
  select(created_at, screen_name, text, retweet_count)
```

### Most liked tweet

```{r}
dog_tweets %>% 
  arrange(-favorite_count) %>%
  top_n(5, favorite_count) %>% 
  select(created_at, screen_name, text, favorite_count)


```

### Top tweeters

```{r}
dog_tweets %>% 
  count(screen_name, sort = TRUE) %>%
  top_n(10) %>%
  mutate(screen_name = paste0("@", screen_name))
```

### Top hashtags

```{r}
library(tidytext)
dog_tweets %>% 
  unnest_tokens(hashtag, text, "tweets", to_lower = FALSE) %>%
  filter(str_detect(hashtag, "^#"),
        hashtag != "#ClimateEmergency") %>%
  count(hashtag, sort = TRUE) %>%
  top_n(10)
```

### Top mentions

```{r}
dog_tweets %>% 
  unnest_tokens(mentions, text, "tweets", to_lower = FALSE) %>%
  filter(str_detect(mentions, "^@")) %>%  
  count(mentions, sort = TRUE) %>%
  top_n(10)
```